export const DEFAULT_PORT = 9000

export const DBMS_MIN_REVISION_WITH_TEMPORARY_TABLES = 50264
export const DBMS_MIN_REVISION_WITH_TOTAL_ROWS_IN_PROGRESS = 51554
export const DBMS_MIN_REVISION_WITH_BLOCK_INFO = 51903
// Legacy above
export const DBMS_MIN_REVISION_WITH_CLIENT_INFO = 54032
export const DBMS_MIN_REVISION_WITH_SERVER_TIMEZONE = 54058
export const DBMS_MIN_REVISION_WITH_QUOTA_KEY_IN_CLIENT_INFO = 54060
export const DBMS_MIN_REVISION_WITH_SERVER_DISPLAY_NAME = 54372
export const DBMS_MIN_REVISION_WITH_VERSION_PATCH = 54401
export const DBMS_MIN_REVISION_WITH_SERVER_LOGS = 54406
export const DBMS_MIN_REVISION_WITH_COLUMN_DEFAULTS_METADATA = 54410
export const DBMS_MIN_REVISION_WITH_CLIENT_WRITE_INFO = 54420

export const DBMS_DEFAULT_CONNECT_TIMEOUT_SEC = 10
export const DBMS_DEFAULT_TIMEOUT_SEC = 300

export const DBMS_NAME = 'ClickHouse'
export const CLIENT_NAME = 'python-driver'
export const CLIENT_VERSION_MAJOR = 0
export const CLIENT_VERSION_MINOR = 0
export const CLIENT_VERSION_PATCH = 1
export const CLIENT_REVISION = 54421
